<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Sound_Player</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Arrow_Down_Search.svg" />
    <None Remove="Resources\Arrow_Up_Search.svg" />
    <None Remove="Resources\Images\Add.svg" />
    <None Remove="Resources\Images\AddMix.svg" />
    <None Remove="Resources\Images\AddRemix.svg" />
    <None Remove="Resources\Images\Apple.svg" />
    <None Remove="Resources\Images\Arrow_Down_Samples.svg" />
    <None Remove="Resources\Images\Arrow_Up_Samples.svg" />
    <None Remove="Resources\Images\BackArrow_Left.svg" />
    <None Remove="Resources\Images\BackArrow_Right.svg" />
    <None Remove="Resources\Images\Bell.svg" />
    <None Remove="Resources\Images\CollapseIcon.svg" />
    <None Remove="Resources\Images\Community.svg" />
    <None Remove="Resources\Images\Cross_Gray.svg" />
    <None Remove="Resources\Images\Cross_White.svg" />
    <None Remove="Resources\Images\Discord.svg" />
    <None Remove="Resources\Images\DoubleArrow_Left.svg" />
    <None Remove="Resources\Images\DoubleArrow_Right.svg" />
    <None Remove="Resources\Images\ExpandWindow.svg" />
    <None Remove="Resources\Images\Facebook.svg" />
    <None Remove="Resources\Images\FullWindowed.svg" />
    <None Remove="Resources\Images\Google.svg" />
    <None Remove="Resources\Images\kish.jpg" />
    <None Remove="Resources\Images\LowVolume.svg" />
    <None Remove="Resources\Images\MiniPlayer.svg" />
    <None Remove="Resources\Images\Mixing.svg" />
    <None Remove="Resources\Images\placeholder.jpg" />
    <None Remove="Resources\Images\placeholder1.jpg" />
    <None Remove="Resources\Images\Planet.svg" />
    <None Remove="Resources\Images\Playlist_Gray.svg" />
    <None Remove="Resources\Images\Playlist_White.svg" />
    <None Remove="Resources\Images\Repeat.svg" />
    <None Remove="Resources\Images\Restart.svg" />
    <None Remove="Resources\Images\SamplasIcon.svg" />
    <None Remove="Resources\Images\Square_TrackBar.svg" />
    <None Remove="Resources\Images\Time.svg" />
    <None Remove="Resources\Images\TreeStripes.svg" />
    <None Remove="Resources\Images\Twitch.svg" />
    <None Remove="Resources\Images\xolidayboy.jpg" />
    <None Remove="Resources\Images\Yandex.svg" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Images\AddRemix.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignColors" Version="5.2.1" />
    <PackageReference Include="MaterialDesignThemes" Version="5.2.1" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="SharpVectors.Wpf" Version="1.8.4.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Model\" />
    <Folder Include="ViewModel\" />
    <Folder Include="View\" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Images\Add.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\AddMix.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Apple.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Arrow_Down_Samples.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Arrow_Down_Search.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Arrow_Up_Samples.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Arrow_Up_Search.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\BackArrow_Left.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\BackArrow_Right.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Bell.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\CollapseIcon.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Community.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Cross_Gray.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Cross_White.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Discord.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\DoubleArrow_Left.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\DoubleArrow_Right.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\ExpandWindow.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Facebook.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\FullWindowed.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Google.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\kish.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Logotype_Blue.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\LowVolume.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\MiniPlayer.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Mixing.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\placeholder.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\placeholder1.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Planet.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Playlist_Gray.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Playlist_White.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Repeat.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Restart.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\SamplasIcon.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Square_TrackBar.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Logotype_White.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Time.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\TreeStripes.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Twitch.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Waves.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\xolidayboy.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\Yandex.svg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
